### ISSUE TITLE
Twitter error response: status code 410

### ISSUE THREAD

**Issue by fredericpoitevin** [fredericpoitevin/cryoEM_PapersBot#1]
The app fails with 

> Traceback (most recent call last):
>   File "./papersbot.py", line 370, in <module>
>     main()
>   File "./papersbot.py", line 358, in main
>     bot = PapersBot(doTweet)
>   File "./papersbot.py", line 247, in __init__
>     twconfig = getTwitterConfig(self.api)
>   File "./papersbot.py", line 186, in getTwitterConfig
>     config = api.configuration()
>   File "/opt/miniconda3/envs/cryoempapers/lib/python3.7/site-packages/tweepy/binder.py", line 252, in _call
>     return method.execute()
>   File "/opt/miniconda3/envs/cryoempapers/lib/python3.7/site-packages/tweepy/binder.py", line 234, in execute
>     raise TweepError(error_msg, resp, api_code=api_error_code)
> tweepy.error.TweepError: Twitter error response: status code = 410

**Comment by fredericpoitevin** [comment]
Issue solved by FX Coudert here: https://github.com/fxcoudert/PapersBot/commit/2d59d26369dd677cd50935b21b0819be8c355c4c

**Comment by fredericpoitevin** [comment]
Abandoning this ship in favor of https://github.com/fredericpoitevin/cryoEMpapersbot which is forked from FX Coudert's PapersBot.
